AWSTemplateFormatVersion: "2010-09-09"
Description: >
  This CloudFormation template creates a role assumed by CloudFormation
  during CRUDL operations to mutate resources on behalf of the customer.

Resources:
  ExecutionRole:
    Type: AWS::IAM::Role
    Properties:
      MaxSessionDuration: 8400
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              Service: resources.cloudformation.amazonaws.com
            Action: sts:AssumeRole
            Condition:
              StringEquals:
                aws:SourceAccount:
                  Ref: AWS::AccountId
              StringLike:
                aws:SourceArn:
                  Fn::Sub: arn:${AWS::Partition}:cloudformation:${AWS::Region}:${AWS::AccountId}:type/resource/AWS-KafkaConnect-Connector/*
      Path: "/"
      Policies:
        - PolicyName: ResourceTypePolicy
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: Allow
                Action:
                - "ec2:CreateNetworkInterface"
                - "ec2:DescribeSecurityGroups"
                - "ec2:DescribeSubnets"
                - "ec2:DescribeVpcs"
                - "firehose:TagDeliveryStream"
                - "iam:CreateServiceLinkedRole"
                - "iam:PassRole"
                - "kafkaconnect:CreateConnector"
                - "kafkaconnect:DeleteConnector"
                - "kafkaconnect:DescribeConnector"
                - "kafkaconnect:ListConnectors"
                - "kafkaconnect:UpdateConnector"
                - "logs:CreateLogDelivery"
                - "logs:DeleteLogDelivery"
                - "logs:DescribeLogGroups"
                - "logs:DescribeResourcePolicies"
                - "logs:GetLogDelivery"
                - "logs:ListLogDeliveries"
                - "logs:PutResourcePolicy"
                - "logs:UpdateLogDelivery"
                - "s3:GetBucketPolicy"
                - "s3:PutBucketPolicy"
                Resource: "*"
Outputs:
  ExecutionRoleArn:
    Value:
      Fn::GetAtt: ExecutionRole.Arn
